# Generated by Django 3.0.3 on 2020-05-04 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courseupdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('subject', models.CharField(max_length=50)),
                ('url', models.URLField(max_length=250)),
                ('desc', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('institution', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=50)),
                ('sub1', models.CharField(blank=True, max_length=50)),
                ('sub2', models.CharField(blank=True, max_length=50)),
                ('sub3', models.CharField(blank=True, max_length=50)),
                ('sub4', models.CharField(blank=True, max_length=50)),
                ('sub5', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
