# Generated by Django 3.0.3 on 2020-05-05 21:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('edclg', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseupdate',
            name='url',
        ),
        migrations.RemoveField(
            model_name='teachers',
            name='sub2',
        ),
        migrations.RemoveField(
            model_name='teachers',
            name='sub3',
        ),
        migrations.RemoveField(
            model_name='teachers',
            name='sub4',
        ),
        migrations.RemoveField(
            model_name='teachers',
            name='sub5',
        ),
        migrations.AddField(
            model_name='courseupdate',
            name='file',
            field=models.FileField(default=django.utils.timezone.now, upload_to='media'),
            preserve_default=False,
        ),
    ]
