# Generated by Django 3.0.3 on 2020-05-07 19:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('edclg', '0003_pdfstore'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseupdate',
            name='unqid',
            field=models.TextField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pdfstore',
            name='unqid',
            field=models.TextField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
