# Generated by Django 3.0.3 on 2020-05-08 11:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('edclg', '0004_auto_20200508_0047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachers',
            name='password',
        ),
        migrations.RemoveField(
            model_name='teachers',
            name='sub1',
        ),
        migrations.AddField(
            model_name='teachers',
            name='email',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
