# Generated by Django 3.0.3 on 2020-05-10 10:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('edclg', '0005_auto_20200508_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfstore',
            name='teacheremail',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
