# Generated by Django 3.0.3 on 2020-05-10 10:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('edclg', '0006_pdfstore_teacheremail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseupdate',
            name='name',
        ),
        migrations.AddField(
            model_name='courseupdate',
            name='email',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
