# Generated by Django 3.0.3 on 2020-05-10 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edclg', '0007_auto_20200510_1547'),
    ]

    operations = [
        migrations.DeleteModel(
            name='pdfstore',
        ),
    ]
