# Generated by Django 3.0.3 on 2020-05-11 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edclg', '0010_pdfstore_unid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfstore',
            name='unid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edclg.Courseupdate'),
        ),
    ]
