# Generated by Django 3.0.3 on 2020-05-11 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edclg', '0011_auto_20200511_2056'),
    ]

    operations = [
        migrations.CreateModel(
            name='coursesingleupdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(default='N/A', max_length=300)),
                ('start_time', models.CharField(blank=True, max_length=5)),
                ('end_time', models.CharField(blank=True, max_length=5)),
                ('days', models.CharField(default='N/A', max_length=30)),
                ('email', models.CharField(default='N/A', max_length=100)),
            ],
        ),
    ]
