# Generated by Django 3.0.3 on 2020-05-14 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edclg', '0016_auto_20200515_0325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpermission',
            name='user',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
