# Generated by Django 3.0.3 on 2020-05-14 21:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('edclg', '0017_auto_20200515_0327'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermission',
            name='usern',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
