# Generated by Django 3.0.3 on 2020-05-15 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edclg', '0018_auto_20200515_0329'),
    ]

    operations = [
        migrations.CreateModel(
            name='student_attend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semail', models.EmailField(max_length=254)),
                ('temail', models.EmailField(max_length=254)),
                ('present', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='student_list_byteach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('college', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
