# Generated by Django 3.0.3 on 2020-05-15 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edclg', '0019_student_attend_student_list_byteach'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_list_byteach',
            name='temail',
            field=models.EmailField(default='teacher email here', max_length=254),
        ),
    ]
