# Generated by Django 3.0.3 on 2020-05-15 15:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('edclg', '0020_student_list_byteach_temail'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_attend',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student_attend',
            name='semail',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='student_attend',
            name='temail',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
